-- A script that creates a database
CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;
CREATE TABLE IF NOT EXISTS states (
id INT UNIQUE AUTO_GENERATED NOT NULL PRIMARY KEY,
name VARCHAR(256) NOT NULL
);
ON hbtn_0d_usa;
